[package]
name = "spellout"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
icu_locid = "1.3.2"
icu_locid_transform = "1.3.2"
